---
abstract: 'Auto-create boolean objects from columns.'
author:
  - 'Bernhard Graf C<< <graf at cpan.org> >>'
  - 'Bernhard Graf <perl-misc@movingtarget.de>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Path::Class: 0
  SQL::Translator: 0
  Scalar::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-InflateColumn-Boolean
no_index:
  directory:
    - inc
    - t
recommends:
  DBD::SQLite: 1.11
requires:
  Contextual::Return: 0.004007
  DBIx::Class: 0.08
resources:
  license: http://dev.perl.org/licenses/
version: 0.002000
